table DimProductCategory
	lineageTag: f411959a-6061-445b-9163-94ae13307a7f

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 7d00684e-8643-4d8d-9c70-34e14a62960d
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductCategoryAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: 9f2a46b0-ca9b-4864-9bc0-6ab918fb4faf
		summarizeBy: none
		sourceColumn: ProductCategoryAlternateKey

		annotation SummarizationSetBy = Automatic

	column EnglishProductCategoryName
		dataType: string
		lineageTag: 81a8f04a-2606-4ab0-8d1f-6b1a24201095
		summarizeBy: none
		sourceColumn: EnglishProductCategoryName

		annotation SummarizationSetBy = Automatic

	column SpanishProductCategoryName
		dataType: string
		lineageTag: 32a2a92c-2219-4ba9-93fa-bf4a71ace825
		summarizeBy: none
		sourceColumn: SpanishProductCategoryName

		annotation SummarizationSetBy = Automatic

	column FrenchProductCategoryName
		dataType: string
		lineageTag: d2f0bf4c-ff57-4967-96b6-ccd553bbd612
		summarizeBy: none
		sourceColumn: FrenchProductCategoryName

		annotation SummarizationSetBy = Automatic

	partition DimProductCategory = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\POwer Bi Udemy 2025\Resource\PowerBIData.xlsx"), null, true),
				    DimProductCategory_Sheet = Source{[Item="DimProductCategory",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimProductCategory_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"ProductCategoryAlternateKey", Int64.Type}, {"EnglishProductCategoryName", type text}, {"SpanishProductCategoryName", type text}, {"FrenchProductCategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

